steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/fastapi-repo/fastapi-app:$COMMIT_SHA',
      '.'
    ]

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/fastapi-repo/fastapi-app:$COMMIT_SHA'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'fastapi-service',
        '--image',
        'us-central1-docker.pkg.dev/$PROJECT_ID/fastapi-repo/fastapi-app:$COMMIT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/fastapi-repo/fastapi-app:$COMMIT_SHA
