name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.VM_IP }} \
          "echo 'Hello from GitHub' >> ~/deploy.txt"
